name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Change this to your JDK version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Change this to your Node.js version

    - name: Cache Gradle and Node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          node_modules
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install
        gradle wrapper --gradle-version 7.4.2 # Use your Gradle version
        gradle build

    - name: Run tests
      run: gradle runTests

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: test/coverage # Path to the coverage report directory
